site_name: 跨过数字鸿沟 Easy-Android-Seniors  # 网站名称
site_url: https://help.csworldlet.top  # 网站 URL（可选）
site_author: Chatseeon  # 网站作者
site_description: >-
  一份指南，帮助老人学会使用安卓手机.A guide to help seniors use Android smartphones  # 网站描述
# Repository
repo_name: chatseeon/easy-android-seniors  # 仓库名称（可选）
repo_url: https://github.com/chatseeon/easy-android-seniors  # 仓库 URL（可选）
# Copyright
copyright: Copyright &copy; 2024 Chatseeon
# Configuration
theme:
  name: material  # 使用 Material 主题
  features:
    - navigation.tabs
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true
# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
# Navigation structure
nav:
  - 首页(Home): index.md
  - 教程(Tutorials):
    - 软件分类(app-category):
      - 聊天(chat):
        - 微信(wechat):
          - 如何加好友(How to add friends): tutorials/app-category/Instant-messaging/wechat/add-friends.md
    - Common Issues: tutorials/common-issues.md
  - Advanced:
    - Security Tips: advanced/security-tips.md
    - Customization: advanced/customization.md
